#!/bin/bash
# ==========================================================================================================================
# Name Script:  zlambda.sh
# Description:  This script allows you to perform actions of a Lambda Function 
#               such as executing locally and deploying to AWS
#
#
# Usage: ./zlambda.sh [-r ARG_R] [-a ARG_A]
#
# Options:
#   -r, --runtime   Specify the runtime AWS or local
#   -a, --action    Specify the action to perform prepare-env, run, deploy
#   -h, --help      Show this help message and exit
#
# Examples:
#   ./zlambda.sh venv
# ==========================================================================================================================
BASE_DIR=$(dirname "$(readlink -f "$0")")
source "$BASE_DIR/lib/utils.sh"
source "$BASE_DIR/lib/commands/manager.command.sh"
source "$BASE_DIR/lib/commands/aws.deploy.command.sh"
source "$BASE_DIR/lib/commands/local.lambda-prepate-env.command.sh"
source "$BASE_DIR/lib/commands/local.lambda-run.sh"

echo "Zlambda CLI - Lambda Development Toolkit"
echo "Version $VERSION"
echo "================================================================================================================="

FILE_CONFIG="config/lambda_config.json"
FILE_CLOUDFORMATION="config/lambda_cloudformation.yml"
FILE_ENV=".local.env"
CONTENT_FILE_CONFIG=$(prepare_json_config $FILE_CONFIG $FILE_ENV)


ARG_RUNTIME=""
ARG_ACTION=""
ARG_ENVIRONMENT=""

while getopts "r:a:e:h:v" opt; do
    case ${opt} in
        r)
            ARG_RUNTIME=${OPTARG}
            ;;
        a)
            ARG_ACTION=${OPTARG}
            ;;
        h)
            show_help
            ;;
        *)
            show_help
            ;;
    esac
done

shift $((OPTIND - 1))
if [[ $# -gt 0 ]]; then
    echo "Error: The following arguments are not supported: $*"
    show_help
fi

case ${ARG_RUNTIME} in
    aws|AWS)
        runtime_aws ${ARG_ACTION}
        ;;
    local|Local)
        validate_is_conda
        runtime_local ${ARG_ACTION} ${CONTENT_FILE_CONFIG}
        ;;
    *)
        echo "Error: Invalid runtime $ARG_RUNTIME"
        show_help
        ;;
esac

